CREATE OR REPLACE PACKAGE PKG_PROVEEDORES AS
    PROCEDURE SP_CREAR_PROVEEDOR(P_NOM IN VARCHAR2, P_TEL IN VARCHAR2, P_MAIL IN VARCHAR2, P_DIR IN VARCHAR2);
    PROCEDURE SP_ACTUALIZAR_PROVEEDOR(P_ID IN NUMBER, P_NOM IN VARCHAR2, P_TEL IN VARCHAR2, P_MAIL IN VARCHAR2, P_DIR IN VARCHAR2);
    PROCEDURE SP_ELIMINAR_PROVEEDOR(P_ID IN NUMBER);
    PROCEDURE SP_LISTAR_PROVEEDORES(P_DATA OUT SYS_REFCURSOR);
    PROCEDURE SP_OBTENER_PROVEEDOR(P_ID IN NUMBER, P_DATA OUT SYS_REFCURSOR);
END PKG_PROVEEDORES;
/

CREATE OR REPLACE PACKAGE BODY PKG_PROVEEDORES AS
    PROCEDURE SP_CREAR_PROVEEDOR(P_NOM IN VARCHAR2, P_TEL IN VARCHAR2, P_MAIL IN VARCHAR2, P_DIR IN VARCHAR2) IS
    BEGIN
        INSERT INTO PROVEEDORES (Nombre, Telefono, Email, Direccion) VALUES (P_NOM, P_TEL, P_MAIL, P_DIR);
        COMMIT;
    END;

    PROCEDURE SP_ACTUALIZAR_PROVEEDOR(P_ID IN NUMBER, P_NOM IN VARCHAR2, P_TEL IN VARCHAR2, P_MAIL IN VARCHAR2, P_DIR IN VARCHAR2) IS
    BEGIN
        UPDATE PROVEEDORES SET Nombre = P_NOM, Telefono = P_TEL, Email = P_MAIL, Direccion = P_DIR WHERE IDProveedor = P_ID;
        COMMIT;
    END;

    PROCEDURE SP_ELIMINAR_PROVEEDOR(P_ID IN NUMBER) IS
    BEGIN
        UPDATE PROVEEDORES SET Estado = 0 WHERE IDProveedor = P_ID;
        COMMIT;
    END;

    PROCEDURE SP_LISTAR_PROVEEDORES(P_DATA OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_DATA FOR SELECT * FROM PROVEEDORES WHERE Estado = 1;
    END;

    PROCEDURE SP_OBTENER_PROVEEDOR(P_ID IN NUMBER, P_DATA OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_DATA FOR SELECT * FROM PROVEEDORES WHERE IDProveedor = P_ID;
    END;
END PKG_PROVEEDORES;
/