CREATE OR REPLACE PACKAGE PKG_COMPRAS AS
    PROCEDURE SP_CREAR_COMPRA(P_IDPROV IN NUMBER, P_IDPROD IN NUMBER, P_CANT IN NUMBER, P_PRECIO IN NUMBER);
    PROCEDURE SP_LISTAR_COMPRAS(P_DATA OUT SYS_REFCURSOR);
    PROCEDURE SP_OBTENER_COMPRA(P_ID IN NUMBER, P_DATA OUT SYS_REFCURSOR);
    PROCEDURE SP_ELIMINAR_COMPRA(P_ID IN NUMBER);
END PKG_COMPRAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_COMPRAS AS
    PROCEDURE SP_CREAR_COMPRA(P_IDPROV IN NUMBER, P_IDPROD IN NUMBER, P_CANT IN NUMBER, P_PRECIO IN NUMBER) IS
        V_ID_COMPRA NUMBER;
        V_SUBTOTAL NUMBER := P_CANT * P_PRECIO;
    BEGIN
        INSERT INTO COMPRAS (IDProveedor, TotalCompra) VALUES (P_IDPROV, V_SUBTOTAL) RETURNING IDCompra INTO V_ID_COMPRA;
        INSERT INTO DETALLE_COMPRA (IDCompra, IDProducto, Cantidad, PrecioCompra, Subtotal)
        VALUES (V_ID_COMPRA, P_IDPROD, P_CANT, P_PRECIO, V_SUBTOTAL);
        UPDATE PRODUCTOS SET StockActual = StockActual + P_CANT WHERE IDProducto = P_IDPROD;
        COMMIT;
    END;

    PROCEDURE SP_LISTAR_COMPRAS(P_DATA OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_DATA FOR SELECT * FROM COMPRAS;
    END;

    PROCEDURE SP_OBTENER_COMPRA(P_ID IN NUMBER, P_DATA OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_DATA FOR SELECT * FROM COMPRAS WHERE IDCompra = P_ID;
    END;

    PROCEDURE SP_ELIMINAR_COMPRA(P_ID IN NUMBER) IS
    BEGIN
        DELETE FROM DETALLE_COMPRA WHERE IDCompra = P_ID;
        DELETE FROM COMPRAS WHERE IDCompra = P_ID;
        COMMIT;
    END;
END PKG_COMPRAS;
/CREATE OR REPLACE PACKAGE PKG_COMPRAS AS
    PROCEDURE SP_CREAR_COMPRA(P_IDPROV IN NUMBER, P_IDPROD IN NUMBER, P_CANT IN NUMBER, P_PRECIO IN NUMBER);
    PROCEDURE SP_LISTAR_COMPRAS(P_DATA OUT SYS_REFCURSOR);
    PROCEDURE SP_OBTENER_COMPRA(P_ID IN NUMBER, P_DATA OUT SYS_REFCURSOR);
    PROCEDURE SP_ELIMINAR_COMPRA(P_ID IN NUMBER);
END PKG_COMPRAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_COMPRAS AS
    PROCEDURE SP_CREAR_COMPRA(P_IDPROV IN NUMBER, P_IDPROD IN NUMBER, P_CANT IN NUMBER, P_PRECIO IN NUMBER) IS
        V_ID_COMPRA NUMBER;
        V_SUBTOTAL NUMBER := P_CANT * P_PRECIO;
    BEGIN
        INSERT INTO COMPRAS (IDProveedor, TotalCompra) VALUES (P_IDPROV, V_SUBTOTAL) RETURNING IDCompra INTO V_ID_COMPRA;
        INSERT INTO DETALLE_COMPRA (IDCompra, IDProducto, Cantidad, PrecioCompra, Subtotal)
        VALUES (V_ID_COMPRA, P_IDPROD, P_CANT, P_PRECIO, V_SUBTOTAL);
        UPDATE PRODUCTOS SET StockActual = StockActual + P_CANT WHERE IDProducto = P_IDPROD;
        COMMIT;
    END;

    PROCEDURE SP_LISTAR_COMPRAS(P_DATA OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_DATA FOR SELECT * FROM COMPRAS;
    END;

    PROCEDURE SP_OBTENER_COMPRA(P_ID IN NUMBER, P_DATA OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_DATA FOR SELECT * FROM COMPRAS WHERE IDCompra = P_ID;
    END;

    PROCEDURE SP_ELIMINAR_COMPRA(P_ID IN NUMBER) IS
    BEGIN
        DELETE FROM DETALLE_COMPRA WHERE IDCompra = P_ID;
        DELETE FROM COMPRAS WHERE IDCompra = P_ID;
        COMMIT;
    END;
END PKG_COMPRAS;
/