CREATE OR REPLACE VIEW VW_LISTA_PROVEEDORES AS 
SELECT Nombre, Telefono, Email FROM PROVEEDORES WHERE Estado = 1;

CREATE OR REPLACE VIEW VW_RESUMEN_COMPRAS AS 
SELECT IDCompra, Fecha, TotalCompra FROM COMPRAS;

CREATE OR REPLACE VIEW VW_DETALLE_HISTORIAL AS 
SELECT C.Fecha, P.Nombre as Proveedor, D.Cantidad, D.PrecioCompra 
FROM COMPRAS C JOIN PROVEEDORES P ON C.IDProveedor = P.IDProveedor
JOIN DETALLE_COMPRA D ON C.IDCompra = D.IDCompra;