CREATE OR REPLACE FUNCTION FN_TOTAL_COMPRA(P_ID NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT TotalCompra INTO V_TOTAL FROM COMPRAS WHERE IDCompra = P_ID;
    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_PROVEEDOR(P_ID NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT SUM(TotalCompra) INTO V_TOTAL FROM COMPRAS WHERE IDProveedor = P_ID;
    RETURN NVL(V_TOTAL, 0);
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_MES RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT SUM(TotalCompra) INTO V_TOTAL FROM COMPRAS WHERE TO_CHAR(Fecha, 'MM') = TO_CHAR(SYSDATE, 'MM');
    RETURN NVL(V_TOTAL, 0);
END;
/

CREATE OR REPLACE FUNCTION FN_PROM_PRODUCTO(P_ID NUMBER) RETURN NUMBER IS
    V_PROM NUMBER;
BEGIN
    SELECT AVG(PrecioCompra) INTO V_PROM FROM DETALLE_COMPRA WHERE IDProducto = P_ID;
    RETURN NVL(V_PROM, 0);
END;
/

CREATE OR REPLACE FUNCTION FN_CONTAR_PROVEEDORES RETURN NUMBER IS
    V_CONT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_CONT FROM PROVEEDORES WHERE Estado = 1;
    RETURN V_CONT;
END;
/